eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/


spring:
  application:
    name: service-feign
  main:
   allow-bean-definition-overriding: true

ribbon:
  eureka:
    enabled: true









  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8084



